# Generated by Django 3.2.19 on 2023-06-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0005_alter_expensecategory_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='category_name',
            field=models.CharField(choices=[('Bills', 'Bills'), ('Clothes', 'Clothes'), ('Entertainment', 'Entertainment'), ('Food', 'Food'), ('Gifts', 'Gifts'), ('Health', 'Health'), ('Pets', 'Pets')], max_length=200, unique=True),
        ),
    ]
