# Generated by Django 3.2.19 on 2023-06-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0008_alter_expensecategory_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcategory',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
