# Generated by Django 3.2.19 on 2023-06-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0011_auto_20230621_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ['category_name']},
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('user', 'category_name'), name='unique_category-per_user'),
        ),
    ]
